apiVersion: v1
kind: Secret
metadata:
  name: ldap-credentials-secret
type: Opaque
stringData:
  credentials: {{ .Values.kerberos.kdc.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hopsworks-app-client-secret
type: Opaque
stringData:
  {{- range .Subcharts.oauth.Values.clients }}
  {{ .id | quote }}: {{ .secret | quote }}
  {{- end }}
