apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kerberos.fullname" . }}-keytabs
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ .Values.keytab.secretName | quote }}]
    verbs: ["get", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kerberos.fullname" . }}-keytabs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kerberos.fullname" . }}-keytabs
subjects:
  - kind: ServiceAccount
    name: {{ include "kerberos.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
