apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: oauth-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for oauth pod only."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth.fullname" . }}
  labels:
    {{- include "oauth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oauth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oauth.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: oauth-high-priority
      serviceAccountName: {{ include "oauth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: configure
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "oauth.image_repository" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - /bin/bash
            - -c
            - |
              nohup /opt/keycloak/bin/kc.sh start-dev &
              sleep 60

              scripts/configure-keycloak.sh
              sleep 10
          env:
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: {{ .Values.kcadmin.username }}
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "oauth.fullname" . }}
                key: kcadmin-password
          - name: CLIENT_JSON_PATH
            value: /resources/client.json          
          - name: USERS_JSON_PATH
            value: /resources/users.json
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "oauth.image_repository" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/keycloak/bin/kc.sh
          args:
            - start-dev
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: {{ .Values.kcadmin.username }}
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "oauth.fullname" . }}
                key: kcadmin-password
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
