apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "oauth.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: client-configuration
data:
  clients.json: |-
{{ tpl (.Files.Get "resources/clients.json") . | indent 8 }}
  groups.json: |-
{{ tpl (.Files.Get "resources/groups.json") . | indent 8 }} 
  users.json: |-
{{ tpl (.Files.Get "resources/users.json") . | indent 8 }}    