apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "oauth.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: client-configuration
data:
  client.json: |-
    {
        "clientId": {{ .Values.client.id | quote }},
        "name": {{ .Values.client.name | quote }},
        "description": {{ .Values.client.description | quote }},
        "rootUrl": {{ .Values.client.rootUrl | quote }},
        "clientAuthenticatorType": "client-secret",
        "secret": {{ .Values.client.secret | quote }},
        "publicClient": false,
        "consentRequired": {{ .Values.client.consentRequired }},
        "redirectUris": {{ .Values.client.redirectUris | toJson }},
        "protocol": "openid-connect",
        "defaultClientScopes": [
            "web-origins",
            "acr",
            "profile",
            "roles",
            "basic",
            "email"
        ],
        "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "organization",
            "microprofile-jwt"
        ]
    }
  users.json: |-
    [
        {
            "username": "alice",
            "email": "alice@hopsworks.ai",
            "emailVerified": true,
            "firstName": "alice",
            "lastName": "alice",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "aliceoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "jdoe",
            "email": "jdoe@hopsworks.ai",
            "emailVerified": false,
            "firstName": "jdoe",
            "lastName": "jdoe",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "jdoeoauth"
                }
            ],
            "groups": [
                "/Users"
            ]
        },
        {
            "username": "admin",
            "email": "admin@hopsworks.ai",
            "emailVerified": true,
            "firstName": "admin",
            "lastName": "admin",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "adminpw"
                }
            ],
            "groups": [
                "/Users",
                "/Admins"
            ],
            "clientRoles": {
                "realm-management": [
                    "realm-admin"
                ]
            }
        },
        {
            "username": "john",
            "email": "john@hopsworks.ai",
            "emailVerified": true,
            "firstName": "John",
            "lastName": "Doe",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "johnoauth"
                }
            ],
            "groups": [
                "/Users",
                "/Admins"
            ] 
        },
        {
            "username": "george",
            "email": "george@hopsworks.ai",
            "emailVerified": true,
            "firstName": "George",
            "lastName": "Doe",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "georgeoauth"
                }
            ],
            "groups": [
                "/Users",
                "/Admins"
            ] 
        },
        {
            "username": "timothy",
            "email": "tkelly@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Timothy",
            "lastName": "Kelly",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "tkellyoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "tim",
            "email": "tlabonte@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Tim",
            "lastName": "Labonte",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "tlabonteoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "torrey",
            "email": "tmason@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Torrey",
            "lastName": "Mason",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "tmasonoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "ted",
            "email": "tmorris@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Ted",
            "lastName": "Morris",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "tmorrisoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "tobias",
            "email": "tpierce@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Tobias",
            "lastName": "Pierce",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "tpierceoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "torrey",
            "email": "trigden@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Torrey",
            "lastName": "Rigden",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "trigdenoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "tobias",
            "email": "tschmith@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Tobias",
            "lastName": "Schmith",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "tschmithoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "torreys",
            "email": "tschneid@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Torrey",
            "lastName": "Schneider",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "tschneidoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "torrey",
            "email": "ttully@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Torrey",
            "lastName": "Tully",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "ttullyoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "tobiasw",
            "email": "tward@hopsworks.ai",
            "emailVerified": true,
            "firstName": "Tobias",
            "lastName": "Ward",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "twardoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        },
        {
            "username": "wendy",
            "email": "wlutzl@hotmail.com",
            "emailVerified": true,
            "firstName": "Wendy",
            "lastName": "Lutz",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "wlutzoauth"
                }
            ],
            "groups": [
                "/Users"
            ] 
        }
    ]