apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "oauth.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "oauth.fullname" . }}
type: Opaque
data:
  {{- if .Values.kcadmin.password }}
  kcadmin-password: {{ .Values.kcadmin.password | b64enc | quote }}
  {{- else }}
  kcadmin-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}