
global:
  realm:  &default_realm hopsworks.ai
  basedn: &baseDN dc=hopsworks,dc=ai
  adminPassword: &admin_password adminpw
  keytabSecretName: &keytabs_secret keytab-secret

  image:
    repository: "docker.hops.works/dev/ermias/hopsworks/test"

kerberos:
  fullnameOverride: kerberos
  keytab:
    secretName: *keytabs_secret
  kdc:
    password: *admin_password
  krb5:
    default_realm: *default_realm
  ldap:
    basedn: *baseDN
    domain: *default_realm
    ou: "Hopsworks Inc."
oauth:
  fullnameOverride: oauth
